
name: checkmate_prod

services:
  client:
    # image: bluewaveuptime/uptime_client:latest
    image: checkmateuptime/client:latest
    build:
      context: .
      dockerfile: Docker/prod/client.Dockerfile
    restart: unless-stopped
    env_file:
      - .env
    environment:
      - NODE_ENV=production
      - VITE_APP_API_BASE_URL=/api/v1
    ports:
      - "5173:80"
    volumes:
      - ./Docker/prod/nginx/conf.d/default.conf:/etc/nginx/conf.d/default.conf
    #   # - ./Client/dist:/usr/share/nginx/html
    depends_on:
      server:
        condition: service_healthy
  server:
    # image: bluewaveuptime/uptime_server:latest
    image: checkmateuptime/server:latest
    build:
      context: .
      dockerfile: Docker/prod/server.Dockerfile
    restart: unless-stopped
    # ports:
    #   - "5000:5000"
    depends_on:
      - redis
      - mongodb
    env_file:
      - .env
    environment:
      - DB_CONNECTION_STRING=mongodb://mongodb:27017/uptime_db
      - REDIS_HOST=redis
    healthcheck:
      test: ['CMD-SHELL', 'wget --spider -q http://server:5000/api-docs/ || exit 1']
      interval: 5s
      timeout: 5s
      retries: 30
    # volumes:
    #  - /var/run/docker.sock:/var/run/docker.sock:ro
  redis:
    image: checkmateuptime/redis:latest
    # image: bluewaveuptime/uptime_redis:latest
    restart: unless-stopped
    volumes:
      - redis_data:/data
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 30s
      timeout: 10s
      retries: 5
      start_period: 5s
  mongodb:
    image: checkmateuptime/mongo:latest
    # image: bluewaveuptime/uptime_database_mongo:latest
    restart: unless-stopped
    volumes:
      - mongo_data:/data/db
    command: ["mongod", "--quiet"]
    ports:
      - "27017:27017"

volumes:
  redis_data:
  mongo_data:

